export interface WordCategory {
  name: string;
  emoji: string;
  description: string;
  words: string[];
}

export const CATEGORIES: WordCategory[] = [
  {
    name: "Party",
    emoji: "🎉",
    description: "Party vibes & celebrations",
    words: [
      "Balloon", "Confetti", "DJ", "Dance Floor", "Karaoke", "Cocktail", "Streamers", "Piñata",
      "Birthday Cake", "Disco Ball", "Champagne", "Toast", "Invitation", "Gift Wrap", "Party Hat",
      "Glow Stick", "Bouncer", "VIP", "Limousine", "Red Carpet", "Photo Booth", "Selfie",
      "Hangover", "Shots", "Beer Pong", "Flip Cup", "Punch Bowl", "Ice Bucket", "Bartender",
      "Nightclub", "Rave", "Festival", "Concert", "Mosh Pit", "Crowd Surf", "Encore",
      "After Party", "House Party", "Pool Party", "Costume Party", "Masquerade", "Toga Party",
      "Bonfire", "Fireworks", "Sparkler", "Candles", "Lantern", "Fairy Lights", "Smoke Machine",
      "Laser Show", "Stage Dive", "Breakdance", "Twerk", "Conga Line", "Limbo", "Musical Chairs",
      "Spin the Bottle", "Truth or Dare", "Charades", "Pictionary", "Trivia Night", "Bingo",
      "Scavenger Hunt", "Escape Room", "Treasure Hunt", "Pinball", "Jukebox", "Keg Stand",
      "Rooftop", "Garden Party", "Barbecue", "Tailgate", "Block Party", "Surprise Party",
      "Bachelor Party", "Bachelorette", "Wedding Reception", "Anniversary", "Graduation Party",
      "Prom", "Homecoming", "New Years Eve", "Halloween Party", "Christmas Party",
      "Valentines Day", "Mardi Gras", "Carnival", "Parade", "Float", "Marching Band",
      "Trumpet", "Saxophone", "Drum", "Bass Drop", "Subwoofer", "Speaker", "Microphone",
      "Spotlight", "Strobe Light", "Fog Machine", "Bubble Machine", "Glitter", "Face Paint",
      "Body Paint", "Temporary Tattoo", "Wristband", "Lanyard", "Ticket", "Cover Charge",
      "Open Bar", "Happy Hour", "Brunch", "Mimosa", "Sangria", "Margarita", "Tequila",
      "Vodka", "Rum", "Whiskey", "Wine", "Prosecco", "Cider", "Mocktail", "Soda",
      "Juice", "Punch", "Lemonade", "Ice Tea", "Energy Drink", "Coffee", "Espresso",
      "Cappuccino", "Latte", "Hot Chocolate", "Smoothie", "Milkshake", "Slushie",
      "Popsicle", "Ice Cream", "Cupcake", "Brownie", "Cookie", "Donut", "Pretzel",
      "Nachos", "Pizza Slice", "Mini Quiche", "Cheese Platter", "Fruit Tray",
      "Chocolate Fountain", "Candy Bar", "Popcorn Machine", "Cotton Candy",
      "Funnel Cake", "Snow Cone", "Caramel Apple", "Churro", "Waffle",
      "Croquette", "Spring Roll", "Sushi Roll", "Slider", "Taco",
      "Bruschetta", "Deviled Egg", "Shrimp Cocktail", "Crab Cake",
      "Stuffed Mushroom", "Meatball", "Chicken Wing", "Rib", "Corn Dog",
      "Hot Dog", "Hamburger", "Cheeseburger", "French Fry", "Onion Ring",
      "Jalapeno Popper", "Mozzarella Stick", "Garlic Bread", "Breadstick",
      "Cracker", "Chip", "Dip", "Salsa", "Guacamole", "Hummus",
      "Pita", "Flatbread", "Naan", "Samosa", "Dumpling", "Wonton",
      "Egg Roll", "Gyoza", "Tempura", "Edamame", "Satay", "Kebab",
      "Falafel", "Poutine", "Arancini", "Ceviche", "Tartare",
      "Carpaccio", "Antipasto", "Charcuterie", "Brie", "Gouda",
      "Cheddar", "Parmesan", "Blue Cheese", "Camembert", "Gruyere"
    ],
  },
  {
    name: "Animals",
    emoji: "🦁",
    description: "Creatures big & small",
    words: [
      "Lion", "Tiger", "Elephant", "Giraffe", "Zebra", "Hippo", "Rhino", "Gorilla",
      "Chimpanzee", "Orangutan", "Baboon", "Lemur", "Koala", "Kangaroo", "Platypus",
      "Wombat", "Tasmanian Devil", "Echidna", "Kiwi Bird", "Emu", "Ostrich", "Penguin",
      "Flamingo", "Pelican", "Toucan", "Parrot", "Macaw", "Cockatoo", "Parakeet",
      "Hummingbird", "Eagle", "Hawk", "Falcon", "Owl", "Vulture", "Condor", "Albatross",
      "Seagull", "Pigeon", "Crow", "Raven", "Magpie", "Robin", "Sparrow", "Finch",
      "Cardinal", "Blue Jay", "Woodpecker", "Heron", "Crane", "Stork", "Swan",
      "Duck", "Goose", "Turkey", "Peacock", "Pheasant", "Quail", "Chicken",
      "Rooster", "Wolf", "Fox", "Coyote", "Jackal", "Hyena", "Cheetah", "Leopard",
      "Panther", "Jaguar", "Puma", "Lynx", "Bobcat", "Wildcat", "Serval", "Ocelot",
      "Bear", "Grizzly", "Polar Bear", "Panda", "Red Panda", "Raccoon", "Badger",
      "Wolverine", "Otter", "Beaver", "Porcupine", "Hedgehog", "Armadillo", "Sloth",
      "Anteater", "Aardvark", "Mole", "Hamster", "Guinea Pig", "Gerbil", "Chinchilla",
      "Rabbit", "Hare", "Squirrel", "Chipmunk", "Prairie Dog", "Meerkat", "Mongoose",
      "Weasel", "Ferret", "Mink", "Stoat", "Skunk", "Bat", "Flying Fox",
      "Dolphin", "Whale", "Orca", "Shark", "Stingray", "Manta Ray", "Seahorse",
      "Octopus", "Squid", "Jellyfish", "Starfish", "Sea Urchin", "Coral", "Clownfish",
      "Swordfish", "Marlin", "Tuna", "Salmon", "Trout", "Bass", "Catfish", "Pike",
      "Barracuda", "Piranha", "Pufferfish", "Anglerfish", "Moray Eel", "Electric Eel",
      "Crocodile", "Alligator", "Komodo Dragon", "Iguana", "Chameleon", "Gecko",
      "Monitor Lizard", "Tortoise", "Sea Turtle", "Rattlesnake", "Cobra", "Python",
      "Anaconda", "Boa Constrictor", "Viper", "Mamba", "Coral Snake", "King Snake",
      "Frog", "Toad", "Salamander", "Newt", "Axolotl", "Caecilian",
      "Butterfly", "Moth", "Dragonfly", "Damselfly", "Ladybug", "Beetle", "Firefly",
      "Grasshopper", "Cricket", "Cicada", "Mantis", "Stick Insect", "Walking Leaf",
      "Ant", "Termite", "Bee", "Wasp", "Hornet", "Mosquito", "Fly", "Spider",
      "Tarantula", "Scorpion", "Centipede", "Millipede", "Caterpillar", "Silkworm",
      "Snail", "Slug", "Earthworm", "Leech", "Crab", "Lobster", "Shrimp", "Crayfish",
      "Hermit Crab", "Horseshoe Crab", "Barnacle", "Clam", "Oyster", "Mussel", "Scallop",
      "Deer", "Elk", "Moose", "Caribou", "Antelope", "Gazelle", "Impala", "Wildebeest",
      "Buffalo", "Bison", "Yak", "Ox", "Bull", "Cow", "Calf", "Horse", "Donkey",
      "Mule", "Zebra", "Camel", "Llama", "Alpaca", "Sheep", "Goat", "Pig", "Boar",
      "Tapir", "Manatee", "Walrus", "Seal", "Sea Lion", "Narwhal", "Beluga",
      "Dugong", "Pangolin", "Okapi", "Quokka", "Capybara", "Chinchilla"
    ],
  },
  {
    name: "Food",
    emoji: "🍕",
    description: "Delicious dishes & ingredients",
    words: [
      "Pizza", "Sushi", "Burger", "Taco", "Pasta", "Ramen", "Pho", "Curry",
      "Pad Thai", "Fried Rice", "Dim Sum", "Dumpling", "Spring Roll", "Noodle Soup",
      "Biryani", "Tikka Masala", "Naan Bread", "Samosa", "Falafel", "Hummus",
      "Kebab", "Shawarma", "Gyro", "Souvlaki", "Moussaka", "Paella", "Risotto",
      "Gnocchi", "Ravioli", "Lasagna", "Carbonara", "Bolognese", "Pesto", "Alfredo",
      "Marinara", "Bruschetta", "Caprese", "Tiramisu", "Gelato", "Cannoli",
      "Panna Cotta", "Biscotti", "Focaccia", "Ciabatta", "Prosciutto", "Mozzarella",
      "Parmesan", "Pecorino", "Mascarpone", "Ricotta", "Gorgonzola",
      "Croissant", "Baguette", "Crepe", "Souffle", "Eclair", "Macaron", "Creme Brulee",
      "Quiche", "Ratatouille", "Bouillabaisse", "Coq au Vin", "Beef Bourguignon",
      "Escargot", "Foie Gras", "Tartare", "Croque Monsieur", "French Onion Soup",
      "Pancake", "Waffle", "French Toast", "Bacon", "Sausage", "Scrambled Eggs",
      "Omelette", "Benedict", "Hash Brown", "Avocado Toast", "Granola", "Yogurt",
      "Smoothie Bowl", "Acai Bowl", "Cereal", "Oatmeal", "Porridge", "Muesli",
      "Steak", "Ribeye", "Filet Mignon", "T-Bone", "Sirloin", "Prime Rib",
      "Lamb Chop", "Pork Chop", "Roast Chicken", "Fried Chicken", "Rotisserie",
      "Turkey", "Duck", "Venison", "Brisket", "Pulled Pork", "Ribs",
      "Hot Dog", "Corn Dog", "Meatball", "Meatloaf", "Pot Roast",
      "Beef Stew", "Chili", "Gumbo", "Jambalaya", "Clam Chowder",
      "Minestrone", "Gazpacho", "Tomato Soup", "Chicken Noodle Soup",
      "Lobster Bisque", "Wonton Soup", "Miso Soup", "Egg Drop Soup",
      "Caesar Salad", "Greek Salad", "Cobb Salad", "Waldorf Salad",
      "Coleslaw", "Potato Salad", "Macaroni Salad", "Fruit Salad",
      "Guacamole", "Salsa", "Pico de Gallo", "Queso", "Nachos",
      "Burrito", "Enchilada", "Quesadilla", "Chimichanga", "Tamale",
      "Churro", "Tres Leches", "Flan", "Empanada", "Arepa",
      "Ceviche", "Plantain", "Black Bean Soup", "Tortilla",
      "Sashimi", "Tempura", "Teriyaki", "Miso", "Edamame",
      "Gyoza", "Tonkatsu", "Udon", "Soba", "Takoyaki",
      "Okonomiyaki", "Onigiri", "Matcha", "Mochi", "Dango",
      "Kimchi", "Bibimbap", "Bulgogi", "Japchae", "Tteokbokki",
      "Kimbap", "Korean Fried Chicken", "Banchan", "Galbi",
      "Peking Duck", "Kung Pao Chicken", "Sweet and Sour", "Mapo Tofu",
      "Char Siu", "Wonton", "Chow Mein", "Lo Mein", "Chop Suey",
      "Egg Foo Young", "General Tso", "Orange Chicken", "Sesame Chicken",
      "Banh Mi", "Pho", "Bun Bo Hue", "Goi Cuon", "Banh Xeo",
      "Fish and Chips", "Shepherd's Pie", "Bangers and Mash",
      "Yorkshire Pudding", "Scone", "Crumpet", "Spotted Dick",
      "Toad in the Hole", "Cornish Pasty", "Haggis",
      "Chocolate Cake", "Cheesecake", "Carrot Cake", "Red Velvet",
      "Brownie", "Cookie", "Cupcake", "Donut", "Cinnamon Roll",
      "Apple Pie", "Pecan Pie", "Pumpkin Pie", "Key Lime Pie",
      "Banana Split", "Sundae", "Milkshake", "Ice Cream Cone",
      "Sorbet", "Frozen Yogurt", "Popsicle", "Snow Cone",
      "Cotton Candy", "Caramel Apple", "Funnel Cake", "Pretzel",
      "Popcorn", "Trail Mix", "Granola Bar", "Beef Jerky",
      "Cheese Puff", "Tortilla Chip", "Potato Chip", "Cracker"
    ],
  },
  {
    name: "Sports",
    emoji: "⚽",
    description: "Athletics & competition",
    words: [
      "Soccer", "Basketball", "Football", "Baseball", "Tennis", "Golf", "Hockey",
      "Cricket", "Rugby", "Volleyball", "Badminton", "Table Tennis", "Boxing",
      "Wrestling", "Judo", "Karate", "Taekwondo", "Fencing", "Archery",
      "Swimming", "Diving", "Water Polo", "Surfing", "Kayaking", "Rowing",
      "Sailing", "Canoeing", "Rafting", "Snorkeling", "Scuba Diving",
      "Track and Field", "Marathon", "Sprint", "Hurdles", "Long Jump",
      "High Jump", "Pole Vault", "Shot Put", "Discus", "Javelin",
      "Hammer Throw", "Decathlon", "Triathlon", "Pentathlon", "Relay Race",
      "Gymnastics", "Trampoline", "Balance Beam", "Parallel Bars", "Rings",
      "Floor Exercise", "Vault", "Uneven Bars", "Pommel Horse", "Still Rings",
      "Figure Skating", "Speed Skating", "Ice Hockey", "Curling", "Bobsled",
      "Luge", "Skeleton", "Ski Jump", "Cross Country Skiing", "Biathlon",
      "Downhill Skiing", "Slalom", "Snowboarding", "Halfpipe", "Moguls",
      "Freestyle Ski", "Alpine Skiing", "Nordic Combined",
      "Cycling", "Mountain Biking", "BMX", "Road Racing", "Velodrome",
      "Skateboarding", "Roller Skating", "Inline Skating", "Roller Derby",
      "Formula One", "NASCAR", "Rally", "Drag Racing", "Go Kart",
      "Motorcycle Racing", "Motocross", "Superbike", "Dirt Bike",
      "Horse Racing", "Polo", "Show Jumping", "Dressage", "Rodeo",
      "Bull Riding", "Barrel Racing", "Calf Roping", "Bronco Busting",
      "Lacrosse", "Field Hockey", "Handball", "Squash", "Racquetball",
      "Pickleball", "Paddle Tennis", "Croquet", "Bocce Ball", "Lawn Bowling",
      "Bowling", "Darts", "Billiards", "Pool", "Snooker",
      "Ping Pong", "Foosball", "Air Hockey", "Shuffleboard",
      "Rock Climbing", "Bouldering", "Rappelling", "Mountaineering",
      "Hiking", "Trail Running", "Orienteering", "Parkour", "Freerunning",
      "Skydiving", "Bungee Jumping", "Base Jumping", "Hang Gliding",
      "Paragliding", "Wingsuit", "Zip Line", "Tightrope Walking",
      "Weightlifting", "Powerlifting", "CrossFit", "Bodybuilding",
      "Strongman", "Arm Wrestling", "Tug of War", "Deadlift", "Bench Press",
      "Squat", "Clean and Jerk", "Snatch",
      "Yoga", "Pilates", "Aerobics", "Zumba", "Spinning",
      "Kickboxing", "Muay Thai", "Capoeira", "Krav Maga", "Aikido",
      "Sumo Wrestling", "MMA", "UFC", "Cage Fighting", "Sparring",
      "Surfing", "Windsurfing", "Kitesurfing", "Wakeboarding", "Water Skiing",
      "Jet Skiing", "Paddleboarding", "Bodyboarding", "Boogie Board",
      "Fishing", "Fly Fishing", "Deep Sea Fishing", "Ice Fishing",
      "Hunting", "Target Shooting", "Trap Shooting", "Skeet Shooting",
      "Paintball", "Airsoft", "Laser Tag", "Dodgeball", "Capture the Flag",
      "Ultimate Frisbee", "Disc Golf", "Cornhole", "Horseshoes",
      "Kickball", "Stickball", "Wiffle Ball", "Softball", "Tee Ball",
      "Touchdown", "Home Run", "Slam Dunk", "Hat Trick", "Hole in One",
      "Grand Slam", "Perfect Game", "Triple Crown", "Gold Medal", "World Record",
      "Penalty Kick", "Free Throw", "Three Pointer", "Field Goal", "Strikeout",
      "Knockout", "Submission", "Technical Foul", "Red Card", "Yellow Card",
      "Offside", "Fumble", "Interception", "Sack", "Double Dribble"
    ],
  },
  {
    name: "Movies",
    emoji: "🎬",
    description: "Cinema & entertainment",
    words: [
      "Blockbuster", "Sequel", "Prequel", "Trilogy", "Franchise", "Remake",
      "Reboot", "Spin Off", "Director's Cut", "Extended Edition",
      "Opening Credits", "Closing Credits", "End Scene", "Post Credits",
      "Plot Twist", "Cliffhanger", "Flashback", "Montage", "Time Skip",
      "Slow Motion", "Fast Forward", "Freeze Frame", "Split Screen",
      "Close Up", "Wide Shot", "Aerial Shot", "Tracking Shot", "Pan",
      "Zoom", "Dolly", "Crane Shot", "Steadicam", "Handheld",
      "Green Screen", "CGI", "Special Effects", "Practical Effects",
      "Stunt Double", "Body Double", "Stand In", "Extra", "Cameo",
      "Leading Role", "Supporting Role", "Villain", "Hero", "Sidekick",
      "Love Interest", "Comic Relief", "Mentor", "Narrator", "Voice Over",
      "Action Movie", "Comedy", "Drama", "Horror", "Thriller",
      "Romance", "Sci Fi", "Fantasy", "Musical", "Documentary",
      "Animation", "Anime", "Western", "Film Noir", "Heist Movie",
      "War Movie", "Spy Movie", "Disaster Movie", "Zombie Movie",
      "Slasher Film", "Found Footage", "Mockumentary", "Biopic",
      "Coming of Age", "Road Trip Movie", "Buddy Cop", "Romantic Comedy",
      "Dark Comedy", "Slapstick", "Parody", "Satire", "Period Drama",
      "Courtroom Drama", "Sports Movie", "Dance Movie", "Concert Film",
      "Silent Film", "Black and White", "Technicolor", "IMAX", "3D Movie",
      "Drive In", "Movie Theater", "Red Carpet", "Premiere", "Film Festival",
      "Sundance", "Cannes", "Venice", "Toronto", "Berlin",
      "Oscar", "Golden Globe", "Emmy", "BAFTA", "Palm d'Or",
      "Best Picture", "Best Director", "Best Actor", "Best Actress",
      "Best Screenplay", "Best Score", "Best Song", "Best Editing",
      "Popcorn", "Soda", "Candy", "Nachos", "Movie Snack",
      "Ticket Stub", "Marquee", "Trailer", "Teaser", "Coming Soon",
      "Box Office", "Opening Weekend", "Flop", "Cult Classic", "Sleeper Hit",
      "Director", "Producer", "Screenwriter", "Cinematographer", "Editor",
      "Composer", "Costume Designer", "Set Designer", "Makeup Artist",
      "Sound Designer", "Foley Artist", "Grip", "Gaffer", "Key Grip",
      "Best Boy", "Boom Operator", "Script Supervisor", "Casting Director",
      "Stunt Coordinator", "Fight Choreographer", "Animal Wrangler",
      "Hollywood", "Bollywood", "Studio Lot", "Sound Stage", "Back Lot",
      "Car Chase", "Explosion", "Fight Scene", "Love Scene", "Death Scene",
      "Training Montage", "Dance Number", "Musical Number", "Dream Sequence",
      "Nightmare", "Chase Scene", "Escape Scene", "Heist Scene",
      "Courtroom Scene", "Battle Scene", "Showdown", "Final Boss",
      "Happy Ending", "Sad Ending", "Open Ending", "Twist Ending",
      "Jump Scare", "Suspense", "Mystery", "Red Herring", "MacGuffin",
      "Fourth Wall", "Breaking Fourth Wall", "Unreliable Narrator",
      "Ensemble Cast", "A List", "B Movie", "Indie Film", "Art House",
      "Foreign Film", "Subtitles", "Dubbed", "Soundtrack", "Film Score",
      "Theme Song", "Leitmotif", "Wilhelm Scream", "Laugh Track",
      "Blooper", "Outtake", "Deleted Scene", "Behind the Scenes",
      "Making Of", "Commentary", "Interview", "Press Tour",
      "Fan Theory", "Easter Egg", "Continuity Error", "Goof",
      "Typecast", "Method Acting", "Improvisation", "Ad Lib",
      "Monologue", "Dialogue", "Soliloquy", "One Liner", "Catchphrase"
    ],
  },
  {
    name: "Space",
    emoji: "🚀",
    description: "Cosmos & exploration",
    words: [
      "Galaxy", "Nebula", "Star", "Supernova", "Black Hole", "White Dwarf",
      "Red Giant", "Neutron Star", "Pulsar", "Quasar", "Magnetar",
      "Solar System", "Sun", "Mercury", "Venus", "Earth", "Mars",
      "Jupiter", "Saturn", "Uranus", "Neptune", "Pluto", "Moon",
      "Asteroid", "Comet", "Meteor", "Meteorite", "Shooting Star",
      "Asteroid Belt", "Kuiper Belt", "Oort Cloud", "Dwarf Planet",
      "Space Station", "International Space Station", "Satellite",
      "Space Shuttle", "Rocket", "Booster", "Launch Pad", "Mission Control",
      "Countdown", "Liftoff", "Orbit", "Re Entry", "Splashdown",
      "Spacewalk", "EVA", "Docking", "Airlock", "Module",
      "Solar Panel", "Heat Shield", "Thruster", "Fuel Tank", "Payload",
      "Telescope", "Hubble", "James Webb", "Observatory", "Radio Telescope",
      "Astronaut", "Cosmonaut", "Space Suit", "Helmet", "Oxygen Tank",
      "Zero Gravity", "Microgravity", "Weightlessness", "Floating",
      "Light Year", "Parsec", "Astronomical Unit", "Red Shift", "Blue Shift",
      "Speed of Light", "Wormhole", "Time Dilation", "Relativity",
      "Dark Matter", "Dark Energy", "Antimatter", "Cosmic Ray",
      "Solar Wind", "Solar Flare", "Sunspot", "Corona", "Eclipse",
      "Lunar Eclipse", "Solar Eclipse", "Transit", "Conjunction",
      "Constellation", "Big Dipper", "Orion", "Cassiopeia", "Polaris",
      "North Star", "Zodiac", "Milky Way", "Andromeda", "Centaurus",
      "Alien", "Extraterrestrial", "UFO", "Flying Saucer", "Roswell",
      "Area 51", "SETI", "First Contact", "Invasion", "Abduction",
      "Warp Drive", "Hyperdrive", "Light Speed", "Teleportation",
      "Cryosleep", "Terraforming", "Colony", "Space Station",
      "Mars Rover", "Curiosity", "Perseverance", "Spirit", "Opportunity",
      "Voyager", "Pioneer", "New Horizons", "Cassini", "Juno",
      "Apollo", "Gemini", "Mercury Program", "Space Race", "Moon Landing",
      "NASA", "SpaceX", "ESA", "Roscosmos", "ISRO", "JAXA",
      "Starship", "Dragon Capsule", "Falcon", "Saturn V", "SLS",
      "Space Tourism", "Virgin Galactic", "Blue Origin", "Orbital Hotel",
      "Gravity", "Atmosphere", "Exosphere", "Ionosphere", "Magnetosphere",
      "Van Allen Belt", "Aurora Borealis", "Northern Lights",
      "Big Bang", "Cosmic Inflation", "Expansion", "Universe",
      "Multiverse", "Parallel Universe", "Singularity", "Event Horizon",
      "Accretion Disk", "Gravitational Wave", "Cosmic Background",
      "Exoplanet", "Habitable Zone", "Goldilocks Zone", "Titan",
      "Europa", "Io", "Ganymede", "Callisto", "Enceladus"
    ],
  },
  {
    name: "Spicy",
    emoji: "🌶️",
    description: "Risqué & provocative",
    words: [
      "Flirting", "Wink", "Pickup Line", "Smooth Talker", "Charmer",
      "Heartbreaker", "Crush", "Love Letter", "Secret Admirer", "Blind Date",
      "Speed Dating", "Online Dating", "Swipe Right", "Match", "DM Slide",
      "First Date", "Candlelight Dinner", "Netflix and Chill", "Cuddle",
      "Spooning", "Pillow Talk", "Bedroom Eyes", "Butterflies",
      "Chemistry", "Sparks Flying", "Electric Touch", "Goosebumps",
      "Blushing", "Shy Smile", "Lip Bite", "Eye Contact", "Double Take",
      "Jealousy", "Love Triangle", "Forbidden Fruit", "Secret Affair",
      "Scandal", "Gossip", "Rumor", "Drama", "Catfight",
      "Breakup", "Makeup", "Rebound", "Ex", "Ghosting",
      "Benching", "Breadcrumbing", "Zombie-ing", "Catfishing", "Gaslighting",
      "Situationship", "Friends with Benefits", "No Strings Attached",
      "One Night Stand", "Walk of Shame", "Morning After", "Regret",
      "Hangover", "Body Shot", "Lap Dance", "Strip Poker",
      "Truth or Dare", "Seven Minutes", "Spin the Bottle", "Kiss Cam",
      "Mistletoe", "French Kiss", "Hickey", "Love Bite", "Lipstick Stain",
      "Perfume", "Cologne", "Aftershave", "Lingerie", "Silk Robe",
      "Bubble Bath", "Hot Tub", "Skinny Dipping", "Sunbathing",
      "Bikini", "Speedos", "Crop Top", "Mini Skirt", "High Heels",
      "Stilettos", "Fishnet", "Leather Jacket", "Tight Jeans",
      "Whipped Cream", "Strawberry", "Chocolate Covered", "Cherry",
      "Champagne Toast", "Rose Petals", "Candles", "Massage Oil",
      "Handcuffs", "Blindfold", "Feather", "Ice Cube", "Whip",
      "Safe Word", "Role Play", "Costume", "Fantasy", "Desire",
      "Seduction", "Temptation", "Lust", "Passion", "Intimate",
      "Sensual", "Provocative", "Risqué", "Naughty", "Taboo",
      "Forbidden", "Guilty Pleasure", "Confession", "Secret",
      "Walk In", "Awkward Moment", "Wrong Room", "Caught Red Handed",
      "Walk of Fame", "Reputation", "Infamous", "Notorious",
      "Bad Boy", "Bad Girl", "Rebel", "Rule Breaker", "Wild Card",
      "Party Animal", "Night Owl", "Free Spirit", "Daredevil",
      "Adrenaline", "Thrill Seeker", "Risk Taker", "Troublemaker",
      "Mischief", "Prank", "Dare", "Challenge", "Bet",
      "Double Dare", "Triple Dog Dare", "No Limits", "All In",
      "Poker Face", "Bluff", "Call My Bluff", "Strip Tease",
      "Slow Dance", "Dirty Dancing", "Grinding", "Twerking",
      "Hot and Cold", "Mixed Signals", "Playing Hard", "Cat and Mouse",
      "Love Hate", "On Again Off Again", "Complicated",
      "Its Complicated", "Open Relationship", "Exclusive",
      "Commitment Issues", "Fear of Missing Out", "YOLO",
      "Bucket List", "Fantasy List", "Dream Date", "Perfect Ten",
      "Eye Candy", "Arm Candy", "Trophy", "Catch", "Keeper"
    ],
  },
  {
    name: "Music",
    emoji: "🎵",
    description: "Tunes, genres & instruments",
    words: [
      "Guitar", "Piano", "Drums", "Violin", "Bass", "Saxophone", "Trumpet",
      "Flute", "Clarinet", "Cello", "Harp", "Accordion", "Harmonica",
      "Ukulele", "Banjo", "Mandolin", "Sitar", "Didgeridoo", "Bagpipes",
      "Xylophone", "Marimba", "Vibraphone", "Steel Drum", "Bongo",
      "Conga", "Tambourine", "Triangle", "Cymbal", "Snare Drum",
      "Kick Drum", "Hi Hat", "Tom Tom", "Cowbell", "Maracas",
      "Pop Music", "Rock", "Jazz", "Blues", "Country",
      "Hip Hop", "Rap", "R&B", "Soul", "Funk",
      "Electronic", "EDM", "House Music", "Techno", "Trance",
      "Dubstep", "Drum and Bass", "Ambient", "Lo Fi", "Chillwave",
      "Classical", "Opera", "Symphony", "Orchestra", "Concerto",
      "Sonata", "Overture", "Aria", "Requiem", "Fugue",
      "Reggae", "Ska", "Dancehall", "Afrobeat", "Bossa Nova",
      "Salsa", "Merengue", "Cumbia", "Tango", "Flamenco",
      "K Pop", "J Pop", "Bollywood", "Celtic", "Gospel",
      "Grunge", "Punk Rock", "Metal", "Heavy Metal", "Death Metal",
      "Indie Rock", "Alternative", "Shoegaze", "Post Punk", "New Wave",
      "Chorus", "Verse", "Bridge", "Intro", "Outro",
      "Hook", "Riff", "Solo", "Breakdown", "Drop",
      "Beat", "Tempo", "Rhythm", "Melody", "Harmony",
      "Chord", "Key", "Scale", "Octave", "Pitch",
      "Treble", "Bass Clef", "Sharp", "Flat", "Natural",
      "Crescendo", "Diminuendo", "Forte", "Piano Dynamic", "Staccato",
      "Legato", "Vibrato", "Tremolo", "Glissando", "Arpeggio",
      "Concert", "Festival", "Gig", "Tour", "Arena",
      "Stadium", "Amphitheater", "Club", "Open Mic", "Jam Session",
      "Encore", "Setlist", "Sound Check", "Backstage", "Green Room",
      "Headliner", "Opener", "Support Act", "Roadie", "Sound Engineer",
      "Producer", "DJ", "MC", "Vocalist", "Frontman",
      "Lead Singer", "Backup Singer", "Band", "Duo", "Trio",
      "Quartet", "Choir", "Chorus Line", "A Cappella", "Karaoke",
      "Album", "EP", "Single", "B Side", "Vinyl",
      "CD", "Cassette", "Streaming", "Playlist", "Mixtape",
      "Record Label", "Debut Album", "Greatest Hits", "Live Album",
      "Remix", "Cover Song", "Mashup", "Sampled", "Original",
      "Grammy", "MTV Award", "Brit Award", "Gold Record", "Platinum Record",
      "Number One Hit", "Top Charts", "Billboard", "One Hit Wonder"
    ],
  },
  {
    name: "Travel",
    emoji: "✈️",
    description: "Destinations & adventures",
    words: [
      "Passport", "Visa", "Boarding Pass", "Luggage", "Suitcase",
      "Backpack", "Carry On", "Checked Bag", "Overhead Bin", "Baggage Claim",
      "Airport", "Terminal", "Gate", "Runway", "Control Tower",
      "Takeoff", "Landing", "Turbulence", "First Class", "Business Class",
      "Economy Class", "Window Seat", "Aisle Seat", "Exit Row",
      "In Flight Meal", "Duty Free", "Customs", "Immigration", "Border Control",
      "Hotel", "Resort", "Hostel", "Airbnb", "Motel",
      "Suite", "Penthouse", "Balcony", "Lobby", "Concierge",
      "Room Service", "Mini Bar", "Checkout", "Check In", "Reservation",
      "Beach", "Island", "Tropical", "Paradise", "Palm Tree",
      "Hammock", "Surfboard", "Snorkel", "Scuba", "Coral Reef",
      "Waterfall", "Lagoon", "Volcano", "Hot Spring", "Geyser",
      "Mountain", "Canyon", "Valley", "Desert", "Oasis",
      "Jungle", "Rainforest", "Safari", "Savanna", "Tundra",
      "Glacier", "Fjord", "Northern Lights", "Midnight Sun",
      "Cruise Ship", "Yacht", "Sailboat", "Ferry", "Canoe",
      "Gondola", "Houseboat", "Catamaran", "Kayak", "Raft",
      "Train", "Bullet Train", "Orient Express", "Sleeper Car", "Dining Car",
      "Station", "Platform", "Rails", "Locomotive", "Caboose",
      "Road Trip", "Highway", "Map", "GPS", "Compass",
      "Hitchhiking", "Camper Van", "RV", "Motorcycle", "Scooter",
      "London", "Paris", "Rome", "Tokyo", "New York",
      "Sydney", "Dubai", "Bangkok", "Barcelona", "Amsterdam",
      "Prague", "Vienna", "Istanbul", "Cairo", "Marrakech",
      "Rio de Janeiro", "Buenos Aires", "Havana", "Reykjavik", "Cape Town",
      "Eiffel Tower", "Colosseum", "Great Wall", "Taj Mahal", "Machu Picchu",
      "Statue of Liberty", "Big Ben", "Sydney Opera House", "Petra",
      "Christ the Redeemer", "Pyramids", "Stonehenge", "Angkor Wat",
      "Souvenir", "Postcard", "Photo Album", "Travel Journal", "Guidebook",
      "Phrasebook", "Translator", "Currency Exchange", "Traveler Check",
      "Street Food", "Local Cuisine", "Food Market", "Night Market",
      "Flea Market", "Bazaar", "Souk", "Antique Shop", "Art Gallery",
      "Museum", "Temple", "Cathedral", "Mosque", "Pagoda",
      "Castle", "Palace", "Fortress", "Ruins", "Monument",
      "National Park", "Nature Reserve", "Wildlife Sanctuary",
      "Camping", "Glamping", "Treehouse", "Igloo", "Yurt",
      "Bungalow", "Villa", "Cabin", "Lodge", "Chalet",
      "Ski Resort", "Spa", "Retreat", "Wellness Center",
      "Jet Lag", "Culture Shock", "Wanderlust", "Bucket List",
      "Gap Year", "Sabbatical", "Nomad", "Digital Nomad", "Expat"
    ],
  },
  {
    name: "Technology",
    emoji: "💻",
    description: "Gadgets & digital world",
    words: [
      "Smartphone", "Laptop", "Tablet", "Desktop", "Monitor",
      "Keyboard", "Mouse", "Trackpad", "Webcam", "Microphone",
      "Headphones", "Speaker", "Bluetooth", "Wi-Fi", "Hotspot",
      "Router", "Modem", "Ethernet", "USB", "Lightning Cable",
      "Charger", "Power Bank", "Battery", "Wireless Charging",
      "App", "Software", "Hardware", "Firmware", "Update",
      "Download", "Upload", "Streaming", "Buffer", "Loading",
      "Cloud", "Server", "Database", "API", "Backend",
      "Frontend", "Full Stack", "DevOps", "Algorithm", "Code",
      "Programming", "Python", "JavaScript", "HTML", "CSS",
      "AI", "Machine Learning", "Neural Network", "Deep Learning",
      "ChatGPT", "Robot", "Automation", "Bot", "Virtual Assistant",
      "Siri", "Alexa", "Google Assistant", "Smart Home", "IoT",
      "Smart Watch", "Fitness Tracker", "Heart Rate Monitor",
      "VR Headset", "Augmented Reality", "Mixed Reality", "Metaverse",
      "Hologram", "3D Printing", "Drone", "Self Driving Car",
      "Electric Vehicle", "Tesla", "Solar Panel", "Wind Turbine",
      "Cryptocurrency", "Bitcoin", "Blockchain", "NFT", "Digital Wallet",
      "Social Media", "Instagram", "TikTok", "Twitter", "Facebook",
      "YouTube", "Twitch", "Reddit", "Discord", "Snapchat",
      "Influencer", "Viral Video", "Meme", "Hashtag", "Trending",
      "Like", "Share", "Comment", "Follow", "Subscribe",
      "Notification", "Push Alert", "Email", "Spam", "Inbox",
      "Password", "Two Factor", "Biometric", "Face ID", "Fingerprint",
      "Encryption", "Firewall", "VPN", "Proxy", "Hacker",
      "Cybersecurity", "Phishing", "Malware", "Virus", "Ransomware",
      "Dark Web", "Tor Browser", "IP Address", "Domain", "Website",
      "Search Engine", "Google", "Browser", "Cookie", "Cache",
      "Pixel", "Resolution", "4K", "HDR", "OLED",
      "Retina Display", "Refresh Rate", "Frame Rate", "FPS",
      "Gaming PC", "Console", "PlayStation", "Xbox", "Nintendo",
      "Game Controller", "Joystick", "VR Controller",
      "Startup", "Silicon Valley", "Venture Capital", "IPO",
      "Unicorn", "Disruptor", "Innovation", "Patent", "Open Source",
      "GitHub", "Stack Overflow", "Debug", "Bug Fix", "Patch",
      "Version Control", "Git", "Repository", "Pull Request", "Merge",
      "Agile", "Sprint", "Scrum", "Kanban", "DevOps Pipeline",
      "Docker", "Kubernetes", "Microservice", "Serverless", "Lambda",
      "Data Center", "Rack", "Fiber Optic", "5G", "Bandwidth",
      "Latency", "Ping", "Lag", "Throughput", "Uptime"
    ],
  },
  {
    name: "Nature",
    emoji: "🌿",
    description: "Earth's wonders",
    words: [
      "Forest", "Jungle", "Rainforest", "Woodland", "Grove",
      "Meadow", "Prairie", "Grassland", "Field", "Pasture",
      "Mountain", "Hill", "Cliff", "Plateau", "Mesa",
      "Valley", "Canyon", "Gorge", "Ravine", "Crevasse",
      "River", "Stream", "Creek", "Brook", "Waterfall",
      "Lake", "Pond", "Marsh", "Swamp", "Wetland",
      "Ocean", "Sea", "Bay", "Lagoon", "Estuary",
      "Beach", "Shore", "Coast", "Dune", "Tide Pool",
      "Reef", "Atoll", "Island", "Peninsula", "Archipelago",
      "Desert", "Oasis", "Sand Storm", "Mirage", "Cactus",
      "Tundra", "Permafrost", "Ice Cap", "Glacier", "Iceberg",
      "Volcano", "Lava", "Magma", "Crater", "Geyser",
      "Hot Spring", "Fumarole", "Obsidian", "Pumice", "Basalt",
      "Cave", "Cavern", "Stalactite", "Stalagmite", "Grotto",
      "Rock", "Boulder", "Pebble", "Gravel", "Sand",
      "Clay", "Mud", "Soil", "Dirt", "Humus",
      "Oak Tree", "Pine Tree", "Maple", "Birch", "Willow",
      "Redwood", "Sequoia", "Baobab", "Palm Tree", "Bamboo",
      "Fern", "Moss", "Lichen", "Ivy", "Vine",
      "Wildflower", "Sunflower", "Daisy", "Rose", "Lily",
      "Tulip", "Orchid", "Lavender", "Poppy", "Daffodil",
      "Mushroom", "Toadstool", "Truffle", "Fungus", "Mold",
      "Sunrise", "Sunset", "Dawn", "Dusk", "Twilight",
      "Rainbow", "Thunder", "Lightning", "Storm", "Hurricane",
      "Tornado", "Typhoon", "Cyclone", "Blizzard", "Hailstorm",
      "Drought", "Flood", "Tsunami", "Earthquake", "Avalanche",
      "Landslide", "Mudslide", "Wildfire", "Forest Fire", "Bushfire",
      "Rain", "Snow", "Sleet", "Hail", "Frost",
      "Dew", "Fog", "Mist", "Cloud", "Cumulus",
      "Season", "Spring", "Summer", "Autumn", "Winter",
      "Equinox", "Solstice", "Migration", "Hibernation", "Metamorphosis",
      "Photosynthesis", "Ecosystem", "Biome", "Habitat", "Biodiversity",
      "Erosion", "Sediment", "Fossil", "Amber", "Petrified Wood",
      "Crystal", "Quartz", "Amethyst", "Diamond", "Emerald",
      "Ruby", "Sapphire", "Opal", "Jade", "Turquoise",
      "Aurora Borealis", "Tide", "Current", "Whirlpool", "Maelstrom",
      "Coral", "Seaweed", "Kelp", "Plankton", "Algae"
    ],
  },
  {
    name: "History",
    emoji: "📜",
    description: "Past events & figures",
    words: [
      "Pharaoh", "Pyramid", "Sphinx", "Hieroglyphics", "Mummy",
      "Toga", "Colosseum", "Gladiator", "Chariot", "Centurion",
      "Emperor", "Senate", "Republic", "Democracy", "Monarchy",
      "King", "Queen", "Prince", "Princess", "Knight",
      "Castle", "Fortress", "Moat", "Drawbridge", "Tower",
      "Sword", "Shield", "Armor", "Lance", "Catapult",
      "Trebuchet", "Battering Ram", "Siege", "Battle", "War",
      "Conquest", "Empire", "Colony", "Revolution", "Independence",
      "Constitution", "Declaration", "Treaty", "Alliance", "Truce",
      "Dynasty", "Feudalism", "Serfdom", "Peasant", "Noble",
      "Baron", "Duke", "Earl", "Lord", "Lady",
      "Pope", "Bishop", "Cardinal", "Monastery", "Cathedral",
      "Crusade", "Pilgrimage", "Inquisition", "Reformation", "Renaissance",
      "Enlightenment", "Industrial Revolution", "Steam Engine", "Railroad",
      "Telegraph", "Telephone", "Electricity", "Light Bulb", "Printing Press",
      "Compass", "Astrolabe", "Sextant", "Navigation", "Exploration",
      "New World", "Silk Road", "Spice Trade", "Gold Rush", "Oregon Trail",
      "Viking", "Longship", "Norse", "Rune", "Berserker",
      "Samurai", "Shogun", "Katana", "Ninja", "Bushido",
      "Spartan", "Athenian", "Olympiad", "Philosopher", "Oracle",
      "Trojan Horse", "Odyssey", "Pantheon", "Parthenon", "Acropolis",
      "Aztec", "Maya", "Inca", "Tenochtitlan", "Machu Picchu",
      "Stonehenge", "Druids", "Celtic", "Gaelic", "Briton",
      "Magna Carta", "Black Plague", "Bubonic", "Quarantine",
      "Salem Witch Trials", "Witch Hunt", "Superstition", "Folklore",
      "Pirate", "Treasure Map", "Jolly Roger", "Plank", "Buccaneer",
      "Privateer", "Galleon", "Armada", "Cannonball", "Musket",
      "Duel", "Pistol", "Bayonet", "Cavalry", "Infantry",
      "General", "Admiral", "Commander", "Lieutenant", "Sergeant",
      "Trench", "No Man's Land", "Barbed Wire", "Machine Gun", "Tank",
      "Submarine", "Aircraft Carrier", "Bomber", "Fighter Plane", "Dogfight",
      "D Day", "Pearl Harbor", "Hiroshima", "Cold War", "Iron Curtain",
      "Berlin Wall", "Space Race", "Moon Landing", "Civil Rights",
      "Suffragette", "Abolitionist", "Emancipation", "Underground Railroad",
      "Boston Tea Party", "Bastille", "Guillotine", "Reign of Terror",
      "Napoleon", "Waterloo", "Exile", "Dictator", "Tyrant",
      "Propaganda", "Censorship", "Espionage", "Code Breaker", "Enigma",
      "Rosetta Stone", "Dead Sea Scrolls", "Archaeology", "Excavation",
      "Artifact", "Relic", "Tomb", "Sarcophagus", "Treasure",
      "Crown Jewels", "Coronation", "Throne", "Scepter", "Royal Court",
      "Ambassador", "Diplomat", "Summit", "Conference", "Accord"
    ],
  },
  {
    name: "Professions",
    emoji: "👔",
    description: "Jobs & careers",
    words: [
      "Doctor", "Nurse", "Surgeon", "Dentist", "Pharmacist",
      "Therapist", "Psychiatrist", "Veterinarian", "Optometrist", "Paramedic",
      "Firefighter", "Police Officer", "Detective", "FBI Agent", "CIA Agent",
      "Spy", "Bodyguard", "Security Guard", "Bouncer", "Lifeguard",
      "Lawyer", "Judge", "Prosecutor", "Defense Attorney", "Paralegal",
      "Teacher", "Professor", "Principal", "Tutor", "Librarian",
      "Scientist", "Researcher", "Lab Technician", "Chemist", "Physicist",
      "Biologist", "Geologist", "Astronomer", "Meteorologist", "Archaeologist",
      "Engineer", "Architect", "Contractor", "Electrician", "Plumber",
      "Carpenter", "Mechanic", "Welder", "Mason", "Roofer",
      "Chef", "Baker", "Butcher", "Bartender", "Sommelier",
      "Waiter", "Hostess", "Barista", "Food Critic", "Nutritionist",
      "Pilot", "Flight Attendant", "Air Traffic Controller", "Captain", "Sailor",
      "Truck Driver", "Bus Driver", "Taxi Driver", "Train Conductor", "Chauffeur",
      "Farmer", "Rancher", "Fisherman", "Lumberjack", "Beekeeper",
      "Florist", "Gardener", "Landscaper", "Park Ranger", "Zookeeper",
      "Actor", "Actress", "Director", "Producer", "Screenwriter",
      "Cinematographer", "Stunt Person", "Voice Actor", "Comedian", "Clown",
      "Magician", "Juggler", "Acrobat", "Trapeze Artist", "Contortionist",
      "Musician", "Singer", "Rapper", "DJ", "Composer",
      "Conductor", "Choreographer", "Dancer", "Ballet Dancer", "Breakdancer",
      "Painter", "Sculptor", "Photographer", "Graphic Designer", "Animator",
      "Illustrator", "Tattoo Artist", "Calligrapher", "Potter", "Glassblower",
      "Fashion Designer", "Model", "Stylist", "Makeup Artist", "Hairdresser",
      "Barber", "Tailor", "Seamstress", "Cobbler", "Jeweler",
      "Journalist", "Reporter", "Anchor", "Editor", "Publisher",
      "Author", "Poet", "Blogger", "Influencer", "Podcaster",
      "Astronaut", "Deep Sea Diver", "Explorer", "Mountaineer", "Spelunker",
      "Archaeologist", "Paleontologist", "Anthropologist", "Sociologist",
      "Psychologist", "Economist", "Politician", "Diplomat", "Ambassador",
      "CEO", "CFO", "CTO", "Manager", "Consultant",
      "Accountant", "Auditor", "Financial Advisor", "Stock Broker", "Trader",
      "Real Estate Agent", "Auctioneer", "Appraiser", "Insurance Agent",
      "Software Developer", "Data Scientist", "Cybersecurity Analyst",
      "Network Admin", "IT Support", "Web Developer", "Game Developer",
      "UX Designer", "Product Manager", "Scrum Master"
    ],
  },
];

export function getRandomWord(categoryNames: string[], usedWords: string[]): { word: string; category: string } {
  const cats = CATEGORIES.filter((c) => categoryNames.includes(c.name));
  if (cats.length === 0) return { word: "Unknown", category: "Unknown" };

  // Collect all available words across selected categories
  const allAvailable = cats.flatMap((c) =>
    c.words.filter((w) => !usedWords.includes(w)).map((w) => ({ word: w, category: c.name }))
  );

  if (allAvailable.length === 0) {
    // Reset if all words used — pick from any selected category
    const allWords = cats.flatMap((c) => c.words.map((w) => ({ word: w, category: c.name })));
    return allWords[Math.floor(Math.random() * allWords.length)];
  }
  return allAvailable[Math.floor(Math.random() * allAvailable.length)];
}

export function getRandomCategory(): string {
  return CATEGORIES[Math.floor(Math.random() * CATEGORIES.length)].name;
}
